DROP DATABASE IF EXISTS RESERVAS_SALAS_DB;
CREATE DATABASE RESERVAS_SALAS_DB;
USE  RESERVAS_SALAS_DB;
CREATE TABLE CLIENTE(
ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
CPF VARCHAR(11) NOT NULL UNIQUE,
NOME TEXT
);

CREATE TABLE PREDIO (
ID_PREDIO INT AUTO_INCREMENT PRIMARY KEY,
NOME TEXT
);
CREATE TABLE SALA(
ID_SALA INT AUTO_INCREMENT PRIMARY KEY,
NUMERO INT NOT NULL UNIQUE,
VALOR_LOCACAO DECIMAL(10,2),
ID_PREDIO INT,
 FOREIGN KEY (ID_PREDIO) REFERENCES PREDIO(ID_PREDIO)
);
CREATE TABLE RESERVAS(
ID_RESERVAS INT AUTO_INCREMENT PRIMARY KEY,
DATA_ENTRADA DATE,
DATA_SAIDA DATE,
VALOR_TOTAL DECIMAL (10,2),
NUMERO INT,
ANDAR INT,
ID_PREDIO INT,
ID_CLIENTE INT,
 FOREIGN KEY (ID_PREDIO) REFERENCES PREDIO(ID_PREDIO),
 FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
);